services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/html/"
    expose:
      - "80"
    deploy: 
      mode: replicated
      replicas: 2

  lb:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 
    ports:
      - "12345:80"


